# Generated by Django 5.0.6 on 2024-06-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name_plural': 'teams'},
        ),
    ]
