# Generated by Django 5.0.6 on 2024-06-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_teams_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='googlePlusLink',
        ),
    ]
