# Generated by Django 5.0.6 on 2024-06-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_teams_googlepluslink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='photo',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
